version: '3.8'
services:
  dcnews:
    build: .
    volumes:
      - ./data/static:/app/static/

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./dc_wx_association_table.sql:/docker-entrypoint-initdb.d/dc_wx_association_table.sql
